apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fourthtanant
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
