apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-test
  name: go-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-test
    spec:
      containers:
      - image: qasim683/go-test:v0.2.0
        name: go-test
        resources: {}
status: {}
